### ISSUE TITLE
Non-HTML Pages

### ISSUE THREAD

**Issue by chrissexton** [velour/holdmypage#22]
When saving non-HTML pages (like a direct link to a PDF or image), the title ends up "Failed to parse page". While this may be true, it's difficult to differentiate links when this happens. It probably ought to just put the URL in as the title when it can't parse the page.

![screenshot from 2015-09-17 09-39-05](https://cloud.githubusercontent.com/assets/3216719/9934530/08517e64-5d20-11e5-985d-d969c48a7fab.png)

**Comment by skiesel** [comment]
I think we know what the default behavior for your account should be when you try to bookmark jpgs.
